const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

test('Bootstrap Icons are loaded and applied to dynamic BusOps controls', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8');
  const server = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');
  const icons = fs.readFileSync(path.join(__dirname, '..', 'public', 'bootstrap-icons-app.js'), 'utf8');
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'passenger-bootstrap.css'), 'utf8');
  assert.match(html, /bootstrap-icons@1\.13\.1\/font\/bootstrap-icons\.min\.css/);
  assert.match(html, /bootstrap-icons-app\.js/);
  assert.match(server, /style-src[^;]+https:\/\/cdn\.jsdelivr\.net/);
  assert.match(server, /font-src[^;]+https:\/\/cdn\.jsdelivr\.net/);
  assert.match(icons, /bi-bus-front-fill/);
  assert.match(icons, /bi-calendar3/);
  assert.match(icons, /bi-luggage-fill/);
  assert.match(icons, /bi-pencil-square/);
  assert.match(icons, /new MutationObserver/);
  assert.match(icons, /function applyBootstrapFoundation\(\)/);
  assert.match(icons, /form-control/);
  assert.match(icons, /table-hover/);
  assert.match(icons, /dashboard-welcome/);
  assert.match(icons, /ops-calendar-shell/);
  assert.match(icons, /function applyBootstrapTripHero\(\)/);
  assert.match(icons, /function applyBootstrapInfoBoards\(\)/);
  assert.match(icons, /function applyBootstrapNewTripDialog\(\)/);
  assert.match(icons, /function applyBootstrapEconomyDashboard\(\)/);
  assert.match(icons, /bootstrap-info-visual/);
  assert.match(icons, /bootstrap-cash-info-card/);
  assert.match(icons, /bi-calendar-event-fill/);
  assert.match(icons, /bi-signpost-split-fill/);
  assert.match(icons, /function applyBootstrapTripKpis\(\)/);
  assert.match(icons, /function applyBootstrapTripTabs\(\)/);
  assert.match(icons, /bootstrap-trip-tab-count/);
  assert.match(icons, /function applyBootstrapExpenseFolder\(\)/);
  assert.match(icons, /function applyBootstrapDashboard\(\)/);
  assert.match(icons, /function applyBootstrapLegacyIcons\(\)/);
  assert.match(icons, /function replaceBusOpsIcon\(/);
  assert.match(icons, /bi-ticket-perforated-fill/);
  assert.match(icons, /data-driver-sales-tab/);
  assert.match(icons, /#driverTicketShortcut > b/);
  assert.match(icons, /#driverBaggageShortcut > b/);
  assert.match(icons, /bi-three-dots/);
  assert.match(icons, /bi-shield-check/);
  assert.match(icons, /bootstrap-cash-flow-arrow/);
  assert.match(icons, /'my-cashbox': 'bi-wallet2'/);
  assert.match(icons, /operations: 'bi-shield-lock-fill'/);
  assert.match(app, /function renderOperationsCenter\(\)/);
  assert.match(css, /\.operations-status-grid/);
  assert.match(icons, /\.picture-bus-icon/);
  assert.match(icons, /#pictureSeatBack/);
  assert.match(icons, /\.expense-card-icon/);
  assert.match(icons, /data-forward-expense/);
  assert.match(icons, /a\[target="_blank"\]/);
  assert.match(icons, /bi-folder2-open/);
  assert.match(icons, /bootstrap-expense-add/);
  assert.match(icons, /bootstrap-dashboard-action-card/);
  assert.match(icons, /data-sales-expense-quick/);
  assert.match(app, /data-sales-expense-quick[^>]*>[\s\S]*?bi-receipt-cutoff/);
  assert.match(app, /bi-receipt-cutoff[^>]*><\/i><\/span><div><strong>Registrer forberedelsesudgift/);
  assert.match(icons, /bi-receipt-cutoff/);
  assert.match(icons, /bi-person-badge/);
  assert.match(icons, /bi-graph-up/);
  assert.match(icons, /dashboard-all-clear/);
  assert.match(icons, /dashboard-all-clear-status/);
  assert.match(icons, /function enhanceBootstrapOperationsCalendar\(\)/);
  assert.match(icons, /function applyBootstrapStopWorkspace\(\)/);
  assert.match(icons, /\.stop-management-hero/);
  assert.match(icons, /bootstrapCalendarInitialized/);
  assert.match(icons, /bootstrap-calendar-filter-toggle/);
  assert.match(icons, /ops-week-card-meta/);
  assert.match(icons, /bi-calendar-week-fill/);
  assert.match(icons, /bi-grid-3x3-gap-fill/);
  assert.match(css, /\.nav>\.nav-bi/);
  assert.match(css, /\.bootstrap-app\{/);
  assert.match(css, /\.bootstrap-dialog/);
  assert.match(css, /\.bootstrap-app \[hidden\]\{display:none!important\}/);
  assert.match(css, /\.bootstrap-trip-hero\{/);
  assert.match(css, /\.trip-hero-status/);
  assert.match(css, /\.bootstrap-info-board\{/);
  assert.match(css, /\.bootstrap-info-visual/);
  assert.match(css, /\.bootstrap-new-trip-button/);
  assert.match(css, /\.bootstrap-new-trip-form/);
  assert.match(css, /\.bootstrap-trip-form-section/);
  assert.match(css, /\.bootstrap-economy-control/);
  assert.match(css, /\.bootstrap-advanced-kpi/);
  assert.match(css, /\.bootstrap-finance-stat/);
  assert.match(css, /\.bootstrap-cash-info-card/);
  assert.match(css, /\.bootstrap-trip-kpis\{grid-template-columns:repeat\(4/);
  assert.match(css, /\.bootstrap-app \.bootstrap-trip-tabs\{/);
  assert.match(css, /\.bootstrap-app \.bootstrap-trip-tab\.active/);
  assert.match(css, /\.bootstrap-operations-calendar/);
  assert.match(css, /\.bootstrap-week-trip-card/);
  assert.match(css, /\.bootstrap-calendar-drawer/);
  assert.match(css, /\.bootstrap-expense-folder/);
  assert.match(css, /\.bootstrap-expense-add\.btn-primary/);
  assert.match(css, /\.bootstrap-dashboard-welcome/);
  assert.match(css, /\.bootstrap-dashboard-action-section/);
  assert.match(css, /\.bootstrap-dashboard-panel/);
  assert.match(css, /grid-template-columns:42px minmax\(0,1fr\) 28px/);
  assert.match(css, /Fælles Bootstrap Icons/);
  assert.match(css, /\.bootstrap-cash-flow-arrow/);
  assert.match(css, /Stoppesteder og live-tidslinje/);
  assert.match(css, /\.stop-management-shell/);
  assert.match(css, /\.live-route-track/);
  assert.match(css, /\.live-bus-marker/);
  assert.doesNotMatch(html, /data-view="(?:dashboard|calendar|stops)"[^>]*>[▦□⌖]/);
  assert.doesNotMatch(app, /Nav\.innerHTML='[♙◫¤▰♟◈⚙]/);
  assert.match(app, /pictureTripInfo\(\).*bi-calendar-event-fill/);
  assert.match(app, /bi-geo-alt-fill/);
  assert.match(app, /bi-bus-front-fill/);
  assert.match(app, /bi-people-fill/);
  assert.match(app, /function renderStopsWorkspace\(\)/);
  assert.match(app, /function tripLiveState\(/);
  assert.match(app, /Estimeret ud fra tidstabellen/);
  assert.match(app, /bi-broadcast-pin/);
  assert.doesNotMatch(app, /pictureTripInfo\(\).*<i>□<\/i>/);
});
