const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

test('passenger and check-in lists use the responsive Bootstrap workspace', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8');
  const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'passenger-bootstrap.css'), 'utf8');
  const app = fs.readFileSync(path.join(__dirname, '..', 'public', 'passenger-bootstrap.js'), 'utf8');
  assert.match(html, /bootstrap@5\.3\.8\/dist\/css\/bootstrap\.min\.css/);
  assert.match(html, /integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8\+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"/);
  assert.match(html, /passenger-bootstrap\.css/);
  assert.match(html, /passenger-bootstrap\.js/);
  assert.match(app, /function bootstrapPassengerCard\(passenger\)/);
  assert.match(app, /function bootstrapPassengerGroups\(passengers\)/);
  assert.match(app, /data-passenger-actions=/);
  assert.match(app, /Ret eller slet/);
  assert.match(app, /function showBootstrapPassengerActionSheet\(id\)/);
  assert.match(app, /passenger-primary-action/);
  assert.match(app, /bi-person-check-fill/);
  assert.match(app, /data-sheet-action="uncheck"/);
  assert.match(app, /Check ind uden betaling/);
  assert.match(app, /Betaling sker i DK/);
  assert.match(app, /Betaling sker i MK/);
  assert.match(app, /externalPaymentConfirmedAt/);
  assert.match(app, /data-sheet-action="confirm-external"/);
  assert.match(app, /openExternalPaymentDialog\('passenger', id\)/);
  assert.match(app, /function passengerTicketStatus\(passenger\)/);
  assert.match(app, /checkin-attendance-badge/);
  assert.match(app, /checkin-payment-badge/);
  assert.match(app, /function reshapeDriverTicketWorkspace\(\)/);
  assert.match(app, /driverSalesTab/);
  assert.match(app, /Billetsalg i bussen/);
  assert.match(app, /function renderDepartureChecklistTab\(\)/);
  assert.match(app, /data-departure-check/);
  assert.match(app, /Afgangskontrol/);
  const mainApp = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8');
  assert.match(mainApp, /function operationalLifecyclePanel\(trip\)/);
  assert.match(mainApp, /operations-action-center/);
  assert.match(mainApp, /renderReportsBeforeFinancialLedger/);
  assert.match(mainApp, /Økonomisk journal/);
  assert.match(mainApp, /function renderNotificationDrafts\(\)/);
  assert.match(mainApp, /data-notification-tab/);
  assert.match(app, /Sortér: Sæde/);
  assert.match(css, /\.bootstrap-passenger-toolbar\{position:sticky/);
  assert.match(css, /@media\(max-width:760px\)\{\.bootstrap-passenger-workspace/);
  assert.match(css, /\.checkin-card\.card/);
  assert.match(css, /\.bootstrap-passenger-action-dialog\{/);
  assert.match(css, /\.passenger-action-journey\{/);
  assert.match(css, /\.bootstrap-passenger-actions \.passenger-action-grid/);
  assert.match(css, /\.checkin-card\.card\.attendance-checked_in/);
  assert.match(css, /\.checkin-payment-badge\.pay-dk/);
  assert.match(css, /\.driver-ticket-workspace\{/);
  assert.match(css, /\.departure-checklist-workspace\{/);
  assert.match(css, /\.external-payment-modal\{/);
  assert.match(css, /\.operational-lifecycle\{/);
  assert.match(css, /\.operations-action-center\{/);
  assert.match(css, /\.financial-ledger\{/);
  assert.match(css, /\.notification-draft-workspace\{/);
});
